"""
Backend discovery, run by the browser bootstrap BEFORE Framework().init(): ask the backend's
__remote_capabilities__ which public interfaces it provides, then write an ordinary module assigning
one make_rpc_proxy(...) class per interface. The framework's normal bundle_prefix scan installs that
module like hand-written code, so a proxy exists before any component depending on it is validated
(unlike a peer backend, whose proxies appear later on a background thread).

The backend only reports, to a caller that is not a peer, the interfaces having @rpc_method methods
(ycappuccino.remote.capabilities) -- exactly those a browser may call. When the backend cannot be asked
(no ycappuccino.remote loaded, network error, malformed answer), the client falls back to
known_interfaces.FALLBACK_INTERFACES.
"""

import inspect
import os

from ycappuccino.api.decorators import get_rpc_methods
from ycappuccino.client.known_interfaces import FALLBACK_INTERFACES, qualified_path
from ycappuccino.client.rpc_proxy import remote_class_name
from ycappuccino.client.transport import HttpTransport, IHttpFetcher, decode_envelope
from ycappuccino.core.component_factory import resolve_class

CAPABILITIES_PATH = "/services/__remote_capabilities__"

_HEADER = '"""Generated by ycappuccino.client.discovery before the framework started. Do not edit."""\n'


async def discover_backend_provides(
    fetcher: IHttpFetcher | None = None, base_url: str | None = None
) -> set | None:
    """the qualified paths the backend reports, or None when it could not be asked"""
    transport = HttpTransport(fetcher=fetcher)
    if base_url is not None:
        # no IConfiguration exists yet: discovery runs before Framework().init()
        transport._base_url = base_url
    try:
        data = decode_envelope(await transport.request("GET", CAPABILITIES_PATH))["data"]
        return {path for component in data.get("components", []) for path in component["provides"]}
    except Exception:
        return None


def enabled_interfaces(discovered: set | None) -> list:
    """(interface, qualified path) to proxy, sorted by path"""
    if discovered is None:
        return [(interface, qualified_path(interface)) for interface in FALLBACK_INTERFACES]
    enabled = []
    for path in sorted(discovered):
        try:
            interface = resolve_class(path)
        except Exception:
            continue
        if inspect.isclass(interface) and inspect.isabstract(interface) and get_rpc_methods(interface):
            enabled.append((interface, path))
    return enabled


def generated_module_source(enabled: list) -> str:
    imports: dict = {}
    for interface, _ in enabled:
        imports.setdefault(interface.__module__, set()).add(interface.__name__)

    lines = [_HEADER]
    for module_name in sorted(imports):
        lines.append(f"from {module_name} import {', '.join(sorted(imports[module_name]))}")
    lines.append("from ycappuccino.client.rpc_proxy import make_rpc_proxy")
    lines.append("")
    used: dict = {}
    for interface, path in enabled:
        name = remote_class_name(interface)
        used[name] = used.get(name, 0) + 1
        if used[name] > 1:
            name = f"{name}{used[name]}"
        lines.append(f"{name} = make_rpc_proxy({interface.__name__}, {path!r})")
    return "\n".join(lines) + "\n"


def write_generated_module(enabled: list, file_path: str) -> None:
    directory = os.path.dirname(file_path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(file_path, "w") as file:
        file.write(generated_module_source(enabled))


def without_client_components(bundle_prefix: list) -> list:
    """bundle_prefix with "ycappuccino.client" replaced by "ycappuccino.client.transport": once a
    generated module provides the proxies, the fallback ones (components.py) must not be installed too"""
    return ["ycappuccino.client.transport" if entry == "ycappuccino.client" else entry for entry in bundle_prefix]


async def prepare_generated_module(
    file_path: str, fetcher: IHttpFetcher | None = None, base_url: str | None = None
) -> list:
    """discovery then generation; returns the qualified paths proxied"""
    enabled = enabled_interfaces(await discover_backend_provides(fetcher=fetcher, base_url=base_url))
    write_generated_module(enabled, file_path)
    return [path for _, path in enabled]
